import { z } from 'zod';

const nullableString = z.string().nullable();
const nullableNumber = z.number().nullable();
const GeoJSONSchema = z
  .object({
    type: z.string(),
    coordinates: z.any(),
  })
  .nullable();


const AbastecimentoBomPratoSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const AbastecimentoFeirasLivresSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const AbastecimentoMercadosMunicipaisSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const AbastecimentoSacolaoSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const CulturaSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_nome: nullableString,
  eq_qtde: nullableNumber,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EducacaoPublicaFundMedSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EducacaoPublicaInfantilSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EducacaoTecnicaPublicaSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_distrit: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_regiao: nullableString,
  eq_subpref: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EsporteClubeSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_tipo: nullableNumber,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tipo: nullableNumber,
  fid: nullableNumber,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EsporteEstadioSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_tipo: nullableNumber,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tipo: nullableNumber,
  fid: nullableNumber,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EsporteOutrosSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_tipo: nullableNumber,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tipo: nullableNumber,
  fid: nullableNumber,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EstacoesMetroSchema = z.object({
  emt_empres: nullableString,
  emt_linha: nullableString,
  emt_nome: nullableString,
  emt_situac: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const EstacoesTremSchema = z.object({
  etr_empres: nullableString,
  etr_linha: nullableString,
  etr_nome: nullableString,
  etr_situac: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const LinhasMetroSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  lmt_empres: nullableString,
  lmt_linha: nullableNumber,
  lmt_linom: nullableString,
  lmt_nome: nullableString,
});

const LinhasOnibusSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  ln_empresa: nullableString,
  ln_nome: nullableString,
  ln_primeir: nullableString,
  ln_ultima: nullableString,
});

const LinhasTremSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  ltr_empres: nullableString,
  ltr_nome: nullableString,
  ltr_numero: nullableNumber,
});

const ParquesUnidadesConservacaoSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  puc_admin: nullableString,
  puc_area: nullableNumber,
  puc_categ: nullableString,
  puc_id: nullableNumber,
  puc_inaug: nullableString,
  puc_instr: nullableString,
  puc_nome: nullableString,
});

const PontosOnibusSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  pt_enderec: nullableString,
  pt_id: nullableNumber,
  pt_nome: nullableString,
});

const PontosShoppingSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  sh_abl: nullableNumber,
  sh_admin: nullableString,
  sh_cep: nullableString,
  sh_constru: nullableNumber,
  sh_enderec: nullableString,
  sh_garagem: nullableNumber,
  sh_id: nullableNumber,
  sh_inaugur: nullableString,
  sh_loja: nullableNumber,
  sh_nome: nullableString,
  sh_piso: nullableNumber,
  sh_salacin: nullableNumber,
  sh_site: nullableString,
  sh_telefon: nullableString,
  sh_terreno: nullableNumber,
});

const ProtecaoMulherSchema = z.object({
  eq_bairro: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_telefon: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaBombeiroSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaBombeiroSadSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaCasaMediacaoSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaCasaMediacaoSadSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaPoliciaCivilSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaPoliciaCivilSadSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaPoliciaMilitarSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const SegurancaPoliciaMilitarSadSchema = z.object({
  eq_bairro: nullableString,
  eq_cd_clas: nullableString,
  eq_cd_esfe: nullableString,
  eq_cd_rede: nullableString,
  eq_cd_tema: nullableString,
  eq_cd_tipo: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_id: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoCatSchema = z.object({
  des_agenda: nullableString,
  des_ender: nullableString,
  des_horari: nullableString,
  des_nome: nullableString,
  des_serv1: nullableString,
  des_serv2: nullableString,
  des_serv3: nullableString,
  des_serv4: nullableString,
  des_sitese: nullableString,
  des_siteun: nullableString,
  des_telefo: nullableNumber,
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_telefon: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoCczSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_telefon: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoConsuladoSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_telefon: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoCorreiosSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_telefon: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoDescomplicaSchema = z.object({
  des_agenda: nullableString,
  des_ender: nullableString,
  des_horari: nullableString,
  des_nome: nullableString,
  des_serv1: nullableString,
  des_serv2: nullableString,
  des_serv3: nullableString,
  des_serv4: nullableString,
  des_sitese: nullableString,
  des_siteun: nullableString,
  des_telefo: nullableNumber,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ServicoEnelSchema = z.object({
  eq_bairro: nullableString,
  eq_cep: nullableString,
  eq_classe: nullableString,
  eq_enderec: nullableString,
  eq_esfera: nullableString,
  eq_horario: nullableString,
  eq_nome: nullableString,
  eq_rede: nullableString,
  eq_telefon: nullableString,
  eq_tema: nullableString,
  eq_tipo: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
});

const ShoppingCentersSchema = z.object({
  geom:GeoJSONSchema,
  gid: z.number(),
  sh_abl: nullableNumber,
  sh_admin: nullableString,
  sh_cep: nullableString,
  sh_constru: nullableNumber,
  sh_enderec: nullableString,
  sh_garagem: nullableNumber,
  sh_id: nullableNumber,
  sh_inaugur: nullableString,
  sh_loja: nullableNumber,
  sh_nome: nullableString,
  sh_piso: nullableNumber,
  sh_salacin: nullableNumber,
  sh_site: nullableString,
  sh_telefon: nullableString,
  sh_terreno: nullableNumber,
});

const TerminalOnibusSchema = z.object({
  cd_identif: nullableNumber,
  cd_tipo_te: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
  nm_termina: nullableString,
  nm_tipo_te: nullableString,
  tx_enderec: nullableString,
});

const TerminalOnibusSad69Schema = z.object({
  cd_identif: nullableNumber,
  cd_tipo_te: nullableString,
  geom:GeoJSONSchema,
  gid: z.number(),
  nm_termina: nullableString,
  nm_tipo_te: nullableString,
  tx_enderec: nullableString,
});

export {
  AbastecimentoBomPratoSchema,
  AbastecimentoFeirasLivresSchema,
  AbastecimentoMercadosMunicipaisSchema,
  AbastecimentoSacolaoSchema,
  CulturaSchema,
  EducacaoPublicaFundMedSchema,
  EducacaoPublicaInfantilSchema,
  EducacaoTecnicaPublicaSchema,
  EsporteClubeSchema,
  EsporteEstadioSchema,
  EsporteOutrosSchema,
  EstacoesMetroSchema,
  EstacoesTremSchema,
  LinhasMetroSchema,
  LinhasOnibusSchema,
  LinhasTremSchema,
  ParquesUnidadesConservacaoSchema,
  PontosOnibusSchema,
  PontosShoppingSchema,
  ProtecaoMulherSchema,
  SegurancaBombeiroSchema,
  SegurancaBombeiroSadSchema,
  SegurancaCasaMediacaoSchema,
  SegurancaCasaMediacaoSadSchema,
  SegurancaPoliciaCivilSchema,
  SegurancaPoliciaCivilSadSchema,
  SegurancaPoliciaMilitarSchema,
  SegurancaPoliciaMilitarSadSchema,
  ServicoCatSchema,
  ServicoCczSchema,
  ServicoConsuladoSchema,
  ServicoCorreiosSchema,
  ServicoDescomplicaSchema,
  ServicoEnelSchema,
  ShoppingCentersSchema,
  TerminalOnibusSchema,
  TerminalOnibusSad69Schema,
};