import natural from "natural";
import path from "path";
import { ConversationIntent } from "../domain/enums/conversation.enums";

const __dirname = path.resolve();
const classifier = new natural.BayesClassifier();

const examples: Record<ConversationIntent, string[]> = {
  [ConversationIntent.FAZER_RECLAMACAO]: [
    "quero reclamar",
    "gostaria de relatar um problema",
    "vou fazer uma reclamação",
    "quero fazer uma reclamação",
    "vou denunciar",
    "denunciar problema",
    "relatar erro",
    "tá dando problema na linha",
    "essa linha é um lixo",
    "tá tudo errado",
    "linha não funciona",
    "a linha não passou",
    "metrô parou",
    "ônibus cheio demais",
    "esperando faz 40 minutos",
    "não aguento mais o atraso",
    "a linha 4310 tá horrível",
    "cadê a 875A?",
    "não veio o ônibus",
    "tá atrasado de novo",
    "reclamação da linha azul",
    "metrô com falha",
    "problema técnico na linha",
    "ônibus quebrou no ponto",
    "ninguém avisou nada",
    "precisa melhorar esse serviço",
    "péssimo atendimento hoje",
    // Novos exemplos
    "essa linha tá um caos",
    "o metrô tá uma vergonha",
    "ônibus da 7020 não passa nunca",
    "tô esperando a 309 faz uma hora",
    "reclamar do atraso da linha verde",
    "o 4310 tá sempre lotado",
    "metrô vermelho tá parado de novo",
    "ninguém resolve nada nessa empresa",
    "tô puto com o serviço",
    "a linha amarela tá insuportável",
    "ônibus da 875A quebrou na avenida",
    "tá um descaso total com a 119",
    "reclamar da superlotação",
    "metrô lilás com defeito hoje",
    "o 8000 tá demorando muito",
    "cadê o ônibus da linha 7000?",
    "serviço tá cada dia pior",
    "tô cansado de esperar o metrô",
    "problema na linha 4310 de novo",
    "ônibus não respeita horário",
    "reclamo todo dia e nada muda",
    "a linha azul tá um desastre",
    "metrô parou no meio do caminho",
    "atraso constante na 7020",
    "ônibus da 309 tá horrível",
  ],

  [ConversationIntent.CONSULTAR_RECLAMACOES]: [
    "quero ver as reclamações",
    "tem reclamações da linha 875A?",
    "o que tão falando da 4310?",
    "alguém reclamou da azul?",
    "relataram problema na linha?",
    "tem relatos da 7020?",
    "me mostra os relatos da linha 309",
    "comentários sobre a 4310",
    "problemas recentes na linha azul",
    "houve reclamações hoje?",
    "alguém falou mal da 119?",
    "pessoal reclamou da 4310?",
    "tiveram problemas com a 875A?",
    "tem comentários da linha 7000?",
    "relatos de atraso na linha azul",
    "onde vejo as reclamações?",
    "relataram algo do metrô hoje?",
    "relatos da linha amarela",
    "tem algo informado da 7020?",
    "usuários reclamaram do trajeto?",
    // Novos exemplos
    "o que tão falando do metrô vermelho?",
    "alguém relatou algo da 8000?",
    "tem reclamação recente da 309?",
    "povo tá reclamando da linha verde?",
    "me diz os problemas da 4310",
    "tem algo da linha lilás hoje?",
    "o que tão dizendo da 7020?",
    "alguém falou da 875A no app?",
    "tem denúncia sobre a linha azul?",
    "usuários falaram da 119 hoje?",
    "o que tão comentando do 7000?",
    "tem relato de falha no metrô?",
    "alguém reclamou da superlotação?",
    "quais os problemas da 4310 hoje?",
    "tem algo reportado da 309?",
    "o que falaram da linha amarela?",
    "tem reclamação da 7020 essa semana?",
    "me mostra o que tão falando da 875A",
    "tem problema relatado no metrô lilás?",
    "o que o pessoal tá dizendo da 8000?",
    "alguém mencionou atraso na 119?",
  ],

  [ConversationIntent.CONSULTAR_LINHA]: [
    "875A",
    "me diz como está a 4310",
    "como tá a linha 7020?",
    "a 309 está rodando?",
    "situação da 8000",
    "como está a 4310?",
    "a 7020 tá vindo?",
    "a 875A está normal?",
    "como está o funcionamento da 4310?",
    "situação da 7020 agora",
    "linha azul está ok?",
    "e a 119 hoje?",
    "qual o status da 309?",
    "a 4310 tá funcionando direito?",
    "me mostra a condição da 875A",
    // Novos exemplos
    "a 7000 tá funcionando?",
    "como tá a linha amarela agora?",
    "qual a situação da 119?",
    "a 7020 tá no horário?",
    "me fala da linha vermelha",
    "a 309 tá normal hoje?",
    "qual o status da 8000?",
    "como tá o metrô lilás?",
    "a 4310 tá operando bem?",
    "me diz o estado da 875A",
    "a linha verde tá ok?",
    "qual a condição da 7020?",
    "a 309 tá com atraso?",
    "como tá a 7000 hoje?",
    "a 119 tá funcionando normal?",
    "me fala da linha azul agora",
    "a 875A tá rodando direitinho?",
    "qual o funcionamento da 4310?",
    "como tá o metrô vermelho hoje?",
    "a 7020 tá com problema?",
  ],

  [ConversationIntent.CONSULTAR_STATUS_ONIBUS]: [
    "status do ônibus 7020",
    "ônibus 875A está funcionando?",
    "a 4310 tá rodando?",
    "ônibus atrasado hoje?",
    "ônibus tá normal?",
    "o 7020 está operando?",
    "309 já passou?",
    "ônibus parou?",
    "como tá o sistema de ônibus?",
    "ônibus da 4310 tá circulando?",
    "a 8000 tá em operação?",
    "qual o status da linha 7020?",
    "ônibus deu problema?",
    "tá tudo certo com os ônibus?",
    "tem algum ônibus parado?",
    // Novos exemplos
    "o 875A tá no ponto?",
    "ônibus da 309 tá funcionando?",
    "a 7000 tá operando normal?",
    "qual a situação dos ônibus da 4310?",
    "o 119 tá rodando hoje?",
    "ônibus da 7020 tá atrasado?",
    "a 8000 já passou no ponto?",
    "tem ônibus da 875A circulando?",
    "o 309 tá com problema?",
    "ônibus da 4310 tá no horário?",
    "qual o status do 7000 agora?",
    "o 119 tá funcionando direitinho?",
    "ônibus da 7020 tá lotado?",
    "a 875A tá com defeito?",
    "tem algum problema com o 309?",
    "ônibus da 8000 tá operando?",
    "o 4310 tá circulando normal?",
    "qual a condição do ônibus 7020?",
    "o 875A tá rodando agora?",
    "tem ônibus da 119 no trajeto?",
  ],

  [ConversationIntent.CONSULTAR_STATUS_METRO]: [
    "metrô está funcionando?",
    "linha azul com problemas?",
    "metrô vermelho parou?",
    "metrô lilás tá normal?",
    "tem atraso na linha verde?",
    "metrô operando bem?",
    "linha amarela tá rodando?",
    "metrô da vermelha parou?",
    "linha paulista atrasou?",
    "tem falha nas estações do metrô?",
    "metrô hoje tá bom?",
    "metrô funcionando agora?",
    "metrô azul tá parado?",
    "tem pane na linha lilás?",
    "metrô deu pau hoje?",
    // Novos exemplos
    "a linha verde tá funcionando?",
    "metrô amarelo tá normal?",
    "qual o status do metrô vermelho?",
    "a linha lilás tá com atraso?",
    "metrô azul tá operando?",
    "tem problema na linha paulista?",
    "o metrô vermelho tá rodando?",
    "linha azul tá com falha?",
    "metrô lilás tá funcionando direitinho?",
    "qual a situação do metrô verde?",
    "a linha amarela tá parada?",
    "metrô vermelho tá com defeito?",
    "tem atraso no metrô azul?",
    "linha lilás tá ok hoje?",
    "metrô funcionando normal agora?",
    "a linha verde tá com problema?",
    "metrô amarelo tá no horário?",
    "qual o estado do metrô lilás?",
    "metrô vermelho tá lotado?",
    "tem pane no metrô azul?",
  ],

  [ConversationIntent.CONSULTAR_SALDO]: [
    "quanto tenho no bilhete único?",
    "consultar saldo do bilhete",
    "saldo no cartão top",
    "ver meu saldo do bom",
    "quanto ainda tenho no bilhete?",
    "saldo atual do transporte",
    "saldo do meu bilhete",
    "ver saldo do cartão",
    "saldo do ônibus",
    "saldo restante",
    "quero ver meu saldo",
    "me diz quanto tenho no bilhete",
    "saldo disponível no bilhete único",
    "saldo no cartão de ônibus",
    "saldo do vale-transporte",
    // Novos exemplos
    "quanto tem no meu cartão top?",
    "saldo do bilhete único agora",
    "me mostra o saldo do bom",
    "quanto sobrou no meu cartão?",
    "ver o saldo do vale-transporte",
    "saldo atual do meu bilhete",
    "me diz o saldo do cartão top",
    "quanto tá no meu bilhete único?",
    "saldo disponível no cartão bom",
    "ver quanto tenho no transporte",
    "saldo do meu cartão de ônibus",
    "me fala o saldo do bilhete",
    "quanto resta no vale-transporte?",
    "saldo no cartão do metrô",
    "me mostra quanto tem no bilhete",
    "saldo atual do cartão top",
    "quanto tá sobrando no bom?",
    "ver saldo do bilhete agora",
    "saldo do meu cartão transporte",
    "me diz quanto sobrou no bilhete",
  ],

  [ConversationIntent.CALCULAR_ROTA]: [
    "quanto tempo até o shopping eldorado?",
    "como chego no trabalho?",
    "me mostra a melhor rota",
    "como faço pra chegar na faculdade?",
    "trajeto até a estação barra funda",
    "calcular rota até casa",
    "qual o melhor caminho até o centro?",
    "rota até a estação vergueiro",
    "melhor caminho até o terminal pinheiros",
    "como ir pro terminal sacomã",
    "quero ir pro shopping santa cruz",
    "melhor trajeto até a paulista",
    "me leva até o aeroporto",
    "caminho até o metrô saúde",
    "rota mais rápida pro trabalho",
    "como ir pra faculdade de manhã",
    "qual rota evita trânsito agora?",
    "quero saber o tempo de trajeto",
    // Novos exemplos
    "como chego no terminal tietê?",
    "qual o trajeto pro shopping morumbi?",
    "rota até a estação luz",
    "melhor caminho pro itaú cultural",
    "como ir pro hospital sírio-libanês?",
    "trajeto até o metrô consolação",
    "qual a rota mais rápida pro anhangabaú?",
    "me leva até o shopping cidade são paulo",
    "caminho pro terminal jabaquara",
    "rota até a avenida faria lima",
    "como chego no ibirapuera?",
    "melhor trajeto pro metrô tatuapé",
    "quanto tempo até o terminal capelinha?",
    "como ir pro shopping d?",
    "qual o caminho pro mis?",
    "trajeto até o metrô vila madalena",
    "rota mais curta pro centro cultural sp",
    "me mostra como chegar na usp",
    "caminho até o terminal santo amaro",
    "qual a melhor rota pro allianz parque?",
    "como chego na estação sé?",
  ],

  [ConversationIntent.SALVAR_LOCAL]: [
    "salvar meu endereço",
    "quero cadastrar minha casa",
    "salvar casa",
    "meu trabalho fica na paulista",
    "salvar localização do trabalho",
    "moro na rua augusta",
    "fica na rua da consolação",
    "meu endereço é na zona norte",
    "quero guardar onde moro",
    "adicionar endereço de casa",
    "quero registrar meu endereço",
    "local fixo casa",
    "local fixo trabalho",
    "endereço principal",
    "adicionar ponto base",
    // Novos exemplos
    "cadastrar meu endereço de casa",
    "salvar onde trabalho",
    "meu endereço é na zona sul",
    "quero salvar meu local de trabalho",
    "adicionar casa no sistema",
    "moro na avenida brasil",
    "salvar meu ponto fixo",
    "trabalho na rua liberdade",
    "cadastrar onde moro",
    "salvar endereço na zona leste",
    "meu local é na vila mariana",
    "quero guardar meu trabalho",
    "adicionar endereço fixo",
    "salvar casa na zona oeste",
    "meu endereço principal é no centro",
    "cadastrar meu ponto de casa",
    "salvar localização na vila madalena",
    "trabalho na faria lima",
    "quero registrar onde moro",
    "salvar meu endereço na zona norte",
  ],

  [ConversationIntent.ATUALIZAR_LOCAL]: [
    "atualizar meu endereço",
    "mudei de casa",
    "novo endereço",
    "meu endereço atual mudou",
    "quero atualizar a localização",
    "trocar endereço",
    "altere meu local de casa",
    "atualize onde moro",
    "moro em outro lugar agora",
    "preciso alterar meu endereço",
    "casa mudou",
    "nova localização de trabalho",
    "localização foi atualizada",
    // Novos exemplos
    "quero mudar meu endereço de casa",
    "atualizar local de trabalho",
    "mudei pra zona sul",
    "novo endereço na vila mariana",
    "alterar onde moro",
    "atualize meu local fixo",
    "mudei pro centro",
    "quero trocar o endereço de casa",
    "novo local de trabalho na paulista",
    "atualizar minha localização agora",
    "mudei de endereço",
    "alterar endereço na zona leste",
    "atualize meu endereço principal",
    "novo local na zona norte",
    "quero mudar onde trabalho",
    "atualizar endereço na vila madalena",
    "mudei pra rua augusta",
    "alterar meu ponto fixo",
    "atualizar casa na zona oeste",
    "novo endereço de trabalho no itaim",
  ],

  [ConversationIntent.AGENDAR_SAIDA]: [
    "quero ser avisado para sair",
    "me lembra de sair às 13h",
    "avisar horário de saída",
    "me avisa quando for hora de ir",
    "me avisa para sair às 8h",
    "quero agendar saída para o trabalho",
    "quero receber alerta para sair",
    "programar saída para compromisso",
    "me alerta quando eu tiver que ir",
    "manda aviso pra eu sair",
    "avisa quando for hora de sair de casa",
    "me chama na hora de sair",
    "sinaliza quando eu tiver que ir",
    "me avisa o melhor horário pra sair",
    // Novos exemplos
    "me avisa pra sair às 16h",
    "quero alerta pra sair pro médico",
    "programar horário de saída às 9h",
    "me lembra de sair pro shopping",
    "avisar quando for hora de ir trabalhar",
    "manda um aviso pra sair às 7h",
    "quero ser notificado pra sair",
    "agendar saída pras 14h",
    "me avisa quando tiver que sair de casa",
    "programar alerta pra sair pro curso",
    "me lembra de sair às 18h",
    "avisar saída pro compromisso às 10h",
    "me notifica na hora de ir pro metrô",
    "quero alerta de saída pras 15h",
    "me avisa pra sair pro aeroporto",
    "programar saída pro trabalho às 6h",
    "manda aviso quando for sair",
    "me lembra de sair pro evento",
    "avisar horário pra ir pra faculdade",
    "me notifica pra sair às 17h",
  ],

  [ConversationIntent.NENHUMA]: [],
};

for (const [intent, phrases] of Object.entries(examples)) {
  phrases.forEach((text) => classifier.addDocument(text.toLowerCase(), intent));
}

classifier.train();

classifier.save(
  path.resolve(__dirname, "./src/models/intent-classifier.json"),
  (err) => {
    if (err) console.error("Erro ao salvar modelo:", err);
    else console.log("Modelo salvo com sucesso.");
  }
);
